# Boundary

::: {.definition name="Boundary of half space"}

Recall the half space is defined as
$$
\mathbb H^n = \{ (x^1, \dots, x^n) : x^n \ge 0 \}
$$
Its boundary is defined as the set
$$
\mathbb \partial H^n = \{ (x^1, \dots, x^n) : x^n = 0 \}
$$
Its interior is the remainder of the set
$$
\mathbb (H^n)^{\circ} = \{ (x^1, \dots, x^n) : x^n > 0 \}
$$


:::

::: {.theorem}

Let $U, V$ be open sets of $\mathbb H^n$. If $f: U \to V$ is a smooth function in $\mathbb H^n$, then $f$ maps interior point
of $\mathbb H^n$ to interior point of $\mathbb H^n$, and boundary points to boundary points.

:::

::: {.definition name="Boundary of manifolds"}

If $M$ is a manifold of dimension $n$, its boundary $\partial M$ is defined as the set of all points that is mapped to
$\partial \mathbb H^n$ by some local chart of $\mathbb M$.

If $\{(U, \phi) \}$ is an atlas of $M$, then $\{ (U \cap \partial M, \phi |_{U \cap \partial M}) \}$ can serve as an
atlas of $\partial M$, where
$$
\phi|_{U \cap \partial M}: (U \cap \partial M) \to \partial \mathbb H^n = \mathbb R^{n - 1}
$$
Hence $\partial M$ has dimension $n - 1$.

> The above atlas maps neighborhoods of $\partial M$ to $\mathbb R^{n-1}$ not $\mathbb H^{n-1}$, violating our definition.
> This is fixed by a diffeomorphism between $\mathbb R^{n-1}$ and any open ball $B$ of $\mathbb R^{n-1}$ that resides in $\mathbb H^{n-1}$.

## Interior Multiplication

::: {.definition name="Interior multiplication"}

If $\beta$ is a $k$-covector on a vector space $V$, the interior multiplication, or *contraction* of $\beta$
with a vector $v \in V$ is the $(k - 1)$-covector
$$
\iota_v \beta (v_2, \dots, v_k) = \beta(v, v_2, \dots, v_k)
$$

Define $\iota_v(\beta) = 0$ for any $0$-covector $\beta$.

:::

::: {.proposition}

For covectors $\alpha^1, \dots, \alpha^k$ on a vector space $V$, and $v \in V$
$$
\iota_v(\alpha^1 \wedge \dots \wedge \alpha^k) = \sum^k_{i=1} (-1)^{i-1} \alpha^i(v)
\alpha^1 \wedge \dots \wedge \hat {\alpha^i} \wedge \dots \wedge \alpha^k
$$

:::

## Boundary Orientation

::: {.proposition}

The inclusion map $i: \partial M \to M$ is smooth, its differential is an injection
from tangent spaces of $\partial M$ to those of $M$. However, such injection is
not a surjection, and in particular $\partial/\partial x_n$ is not in the range
for any local chart $(x^1, \dots, x^n)$ of $M$.

:::

> At a point $p \in \partial M$, identify the tangent space $T_p(\partial M)$ as a
> subspace of $T_pM$ by the above proposition.

::: {.definition name="Outward pointing vector"}

A vector $X$ of $T_pM \setminus T_p \partial M$ at $p \in \partial M$ is said to be *inward pointing* if there exists curve
$c: (-1, 1) \to M$ such that

1. $c(0, 1) \subset M^\circ$
1. $c(0) = p$
2. $c'(0) = X$

The vector $X$ is outward pointing if $-X$ is inward pointing.

:::

::: {.definition name="Smooth outward pointing vector field"}

A vector field *along* $\partial M$ assigns each $p \in \partial M$ a vector $X_p \in T_pM$. Such
vector field is said to be smooth at $p$ if written in local coordinates of $M$,
$$
X = \sum a_i \frac{\partial}{\partial x^i}
$$
$a_i$ is smooth at $p$ in $\partial M$, i.e., $a_i \in C^\infty_p(\partial M)$.

:::

::: {.theorem}

There exists a smooth outward pointing vector field along $\partial M$ for any smooth manifold $M$.

:::

::: {.theorem}

If $\omega$ is an orientation form of $M$, and $X$ is a smooth outward pointing vector field
along $\partial M$, then $\iota_X\omega$ is an orientation form of $\partial M$.

:::